import tkinter as tk
from tkinter import ttk
from ttkbootstrap import Style
import random




quotes = [
    "No pain, no gain.",
    "The only bad workout is the one that didn't happen.",
    "Strive for progress, not perfection.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Success starts with self-discipline.",
    "The difference between try and triumph is a little 'umph'.",
    "Push yourself because no one else is going to do it for you.",
    "It never gets easier. You just get stronger.",
    "The only way to finish is to start.",
    "You don't have to be great to start, but you have to start to be great.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Your body is your most priceless possession. Take care of it.",
    "The last three or four reps is what makes the muscle grow.",
    "Sweat is magic. Cover yourself in it daily to grant your health wishes.",
    "Your health account is like your bank account: The more you put in, the more you can take out.",
    "Strive for greatness and never settle for mediocrity.",
    "Excuses don't burn calories.",
    "Success is what comes after you stop making excuses.",
    "When you feel like quitting, think about why you started.",
    "You don't get what you wish for; you get what you work for.",
    "The body achieves what the mind believes.",
    "Fitness is not about being better than someone else; it's about being better than you used to be.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "The only place where success comes before work is in the dictionary.",
    "The clock is ticking. Are you becoming the person you want to be?",
    "A year from now, you'll wish you had started today.",
    "Your only limit is you.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "If it doesn't challenge you, it doesn't change you.",
    "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.",
    "Don't limit your challenges; challenge your limits.",
    "Success is the sum of small efforts, repeated day in and day out.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "Work hard in silence; let success make the noise.",
    "Discipline is doing what needs to be done, even if you don't want to do it.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Your mind will quit a thousand times before your body will. Feel the fear and do it anyway.",
    "You are far too smart to be the only thing standing in your way.",
    "Don't wish for a good body; work for it.",
    "In the end, we only regret the workouts we didn't do.",
    "Be proud, but never satisfied.",
    "Your fitness is 100% mental. Your body won't go where your mind doesn't push it.",
    "The only time success comes before work is in the dictionary.",
    "One workout at a time. One day at a time. One meal at a time.",
    "The only failure is not to try.",
    "Every step is progress, no matter how small.",
    "Your health is an investment, not an expense.",
    "A champion is someone who gets up when they can't.",
    "When you feel like quitting, remember why you started.",
    "Hustle for that muscle.",
    "If it doesn't challenge you, it won't change you.",
    "The harder you work, the luckier you get.",
    "Stop doubting yourself; work hard, and make it happen.",
    "You don't have to be extreme, just consistent.",
    "The first step to getting anywhere is deciding you're not willing to stay where you are.",
    "You don't need more time; you need more consistency.",
    "If it doesn't challenge you, it doesn't change you.",
    "It's going to be a journey. It's not a sprint to get in shape.",
    "Do something today that your future self will thank you for.",
    "Make yourself proud.",
    "You are stronger than you know.",
    "Fall in love with taking care of your body.",
    "If you wait for perfect conditions, you'll never get anything done.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Every day is another chance to get stronger, to eat better, to live healthier, and to be the best version of you.",
    "Train like a beast, look like a beauty.",
    "You don't have to go fast, you just have to go.",
    "The only bad workout is the one you didn't do.",
    "Set goals, smash them, and repeat.",
    "A little progress each day adds up to big results.",
    "Make your body the sexiest outfit you own.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "Believe you can, and you're halfway there.",
    "The only time you have is now.",
    "Your future self is begging you to stop procrastinating.",
    "Don't stop until you're proud.",
    "Don't wish for it; work for it.",
    "When you feel like quitting, think about why you started.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "It's never too late to be what you might have been.",
    "If you want it, you'll find a way. If you don't, you'll find an excuse.",
    "The expert in anything was once a beginner.",
    "You don't have to be great to start, but you have to start to be great.",
    "Strive for progress, not perfection.",
    "You are your only limit.",
    "The secret of getting ahead is getting started.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Push yourself because no one else is going to do it for you.",
    "Make yourself a priority.",
    "The only bad workout is the one you didn't do.",
    "When you feel like quitting, think about why you started.",
    "You are far too smart to be the only thing standing in your way.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't stop when you're tired; stop when you're done.",
    "Be stronger than your excuses.",
    "You don't have to be extreme; just consistent.",
    "The first step to getting anywhere is deciding you're not willing to stay where you are.",
    "Suck it up. And one day, you won't have to suck it in.",
    "Your only limit is you.",
    "It's not about having time; it's about making time.",
    "Good things come to those who sweat.",
    "It's going to be a journey. It's not a sprint to get in shape.",
    "The only bad workout is the one you didn't do.",
    "Don't wait for opportunity. Create it.",
    "Set goals. Stay quiet about them. Smash the hell out of them. Clap for your damn self.",
    "In two weeks, you'll feel it. In four weeks, you'll see it. In eight weeks, you'll hear it.",
    "Wake up with determination. Go to bed with satisfaction.",
    "If you're tired of starting over, stop giving up.",
    "You don't get what you wish for; you get what you work for.",
    "The difference between try and triumph is a little 'umph'.",
    "Do something today that your future self will thank you for.",
    "You can't cross the sea merely by standing and staring at the water.",
    "The best way to predict your future is to create it.",
    "Don't wish for it; work for it.",
    "Dream it. Believe it. Build it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "If you want to achieve greatness stop asking for permission.",
    "I find that the harder I work, the more luck I seem to have.",
    "The harder you work, the luckier you get.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The journey of a thousand miles begins with one step.",
    "You are never too old to set another goal or to dream a new dream.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don't count the days. Make the days count.",
    "You miss 100 percent of the shots you don't take.",
    "Your time is limited, don't waste it living someone else's life.",
    "If you want to achieve greatness stop asking for permission.",
    "I find that the harder I work, the more luck I seem to have.",
    "The harder you work, the luckier you get.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The journey of a thousand miles begins with one step.",
    "You are never too old to set another goal or to dream a new dream.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Don't count the days. Make the days count.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "Your health is an investment, not an expense.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "Success is what comes after you stop making excuses.",
    "When you feel like quitting, think about why you started.",
    "It's never too late to be what you might have been.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "You are far too smart to be the only thing standing in your way.",
    "Every day is another chance to get stronger, to eat better, to live healthier, and to be the best version of you.",
    "The first step to getting anywhere is deciding you're not willing to stay where you are.",
    "If you want it, you'll find a way. If you don't, you'll find an excuse.",
    "The expert in anything was once a beginner.",
    "You don't have to be great to start, but you have to start to be great.",
    "Strive for progress, not perfection.",
    "You are your only limit.",
    "The secret of getting ahead is getting started.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Push yourself because no one else is going to do it for you.",
    "Make yourself a priority.",
    "The only bad workout is the one you didn't do.",
    "When you feel like quitting, think about why you started.",
    "You are far too smart to be the only thing standing in your way.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Don't stop when you're tired; stop when you're done.",
    "Be stronger than your excuses.",
    "You don't have to be extreme; just consistent.",
    "The first step to getting anywhere is deciding you're not willing to stay where you are.",
    "Suck it up. And one day, you won't have to suck it in.",
    "Your only limit is you.",
    "It's not about having time; it's about making time.",
    "Good things come to those who sweat.",
    "It's going to be a journey. It's not a sprint to get in shape.",
    "The only bad workout is the one you didn't do.",
    "Don't wait for opportunity. Create it.",
    "Set goals. Stay quiet about them. Smash the hell out of them. Clap for your damn self.",
    "In two weeks, you'll feel it. In four weeks, you'll see it. In eight weeks, you'll hear it.",
    "Wake up with determination. Go to bed with satisfaction.",
    "If you're tired of starting over, stop giving up.",
    "You don't get what you wish for; you get what you work for.",
    "The difference between try and triumph is a little 'umph'.",
    "Do something today that your future self will thank you for.",
    "You can't cross the sea merely by standing and staring at the water.",
    "You miss 100 percent of the shots you don't take.",
    "The best way to predict your future is to create it.",
    "Don't wish for it; work for it.",
    "Dream it. Believe it. Build it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.",
    "You are never too old to set another goal or to dream a new dream.",
    "Your time is limited, don't waste it living someone else's life.",
    "If you want to achieve greatness stop asking for permission."]



def show_random_quote():
    quote = random.choice(quotes)
    quote_label.config(text=quote)

app = tk.Tk()
app.title("Fitness Motivation Quote Generator")

# Create ttkbootstrap style
style = Style()

# Create a frame with padding
frame = ttk.Frame(app, padding="20")
frame.pack()

quote_label = ttk.Label(frame, text="", wraplength=350, font=("Arial", 12), padding=10)
quote_label.pack()

generate_button = ttk.Button(frame, text="Generate Quote", command=show_random_quote)
generate_button.pack(pady=10)

app.mainloop()
